[package]
name = "ca-formats"
version = "0.2.2"
authors = ["AlephAlpha <alephalpha911@gmail.com>"]
edition = "2018"
description = "Parsing pattern files for Conway's Game of Life."
homepage = "https://github.com/AlephAlpha/ca-formats"
repository = "https://github.com/AlephAlpha/ca-formats"
license = "MIT"
readme = "README_en.md"
keywords = ["game-of-life", "cellular-automata", "parser"]

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.1"
thiserror = "1.0.21"
