[package]
name = "ca-formats"
version = "0.3.1"
authors = ["AlephAlpha <alephalpha911@gmail.com>"]
edition = "2018"
description = "Parsing pattern files for Conway's Game of Life."
homepage = "https://github.com/AlephAlpha/ca-formats"
repository = "https://github.com/AlephAlpha/ca-formats"
license = "MIT"
readme = "README_en.md"
keywords = ["game-of-life", "cellular-automata", "parser"]

[dependencies]
lazy-regex = "2.0.1"
regex = "1.5.4"
thiserror = "1.0.25"

[features]
default = []
unknown = []
